"""create Penalty

Revision ID: f9a9a182c2da
Revises: 66918c29ffe0
Create Date: 2024-03-15 13:19:59.610025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a9a182c2da'
down_revision = '66918c29ffe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penalty',
    sa.Column('penalty_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('engineers_number', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(), autoincrement=False, nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engineers_number'], ['engineer.engineers_number'], ),
    sa.PrimaryKeyConstraint('penalty_id')
    )
    op.add_column('order', sa.Column('agreement_id', sa.BigInteger(), nullable=True))
    op.add_column('order', sa.Column('prepayment_id', sa.BigInteger(), nullable=True))
    op.add_column('order', sa.Column('stationary_id', sa.BigInteger(), nullable=True))
    op.add_column('order', sa.Column('report_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'order', 'prepayment', ['prepayment_id'], ['prepayment_id'])
    op.create_foreign_key(None, 'order', 'stationary', ['stationary_id'], ['stationary_id'])
    op.create_foreign_key(None, 'order', 'agreement', ['agreement_id'], ['agreement_id'])
    op.create_foreign_key(None, 'order', 'report', ['report_id'], ['report_id'])
    op.add_column('report', sa.Column('advance_payment', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'advance_payment')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'report_id')
    op.drop_column('order', 'stationary_id')
    op.drop_column('order', 'prepayment_id')
    op.drop_column('order', 'agreement_id')
    op.drop_table('penalty')
    # ### end Alembic commands ###
