"""create Penalty1

Revision ID: aee923e33273
Revises: c152b1bf5ac4
Create Date: 2024-03-15 13:49:10.950952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee923e33273'
down_revision = 'c152b1bf5ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('agreement_id', sa.BigInteger(), nullable=True))
    op.add_column('order', sa.Column('prepayment_id', sa.BigInteger(), nullable=True))
    op.add_column('order', sa.Column('stationary_id', sa.BigInteger(), nullable=True))
    op.add_column('order', sa.Column('report_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'order', 'prepayment', ['prepayment_id'], ['prepayment_id'])
    op.create_foreign_key(None, 'order', 'stationary', ['stationary_id'], ['stationary_id'])
    op.create_foreign_key(None, 'order', 'agreement', ['agreement_id'], ['agreement_id'])
    op.create_foreign_key(None, 'order', 'report', ['report_id'], ['report_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'report_id')
    op.drop_column('order', 'stationary_id')
    op.drop_column('order', 'prepayment_id')
    op.drop_column('order', 'agreement_id')
    # ### end Alembic commands ###
