"""create prepayment/TypeOfPayment 1

Revision ID: 602bfe95a53d
Revises: b8de35c64df9
Create Date: 2024-03-13 22:25:58.860690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602bfe95a53d'
down_revision = 'b8de35c64df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prepayment', sa.Column('amount', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prepayment', 'amount')
    # ### end Alembic commands ###
