"""create OutlayRecord

Revision ID: 806b09c353dd
Revises: 602bfe95a53d
Create Date: 2024-03-14 18:55:37.094122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806b09c353dd'
down_revision = '602bfe95a53d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outlay_record',
    sa.Column('outlay_record_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('cheque', sa.String(), autoincrement=False, nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('outlay_record_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outlay_record')
    # ### end Alembic commands ###
