"""create OutlayRecord1

Revision ID: b4a10a290db2
Revises: 806b09c353dd
Create Date: 2024-03-14 18:59:37.378936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a10a290db2'
down_revision = '806b09c353dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outlay_record', sa.Column('order_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'outlay_record', 'order', ['order_id'], ['order_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outlay_record', type_='foreignkey')
    op.drop_column('outlay_record', 'order_id')
    # ### end Alembic commands ###
