"""create prepayment/TypeOfPayment

Revision ID: b8de35c64df9
Revises: 8dc86fd09144
Create Date: 2024-03-13 22:15:07.996977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8de35c64df9'
down_revision = '8dc86fd09144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_of_payment',
    sa.Column('tp_of_pmt_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type_of_payment', sa.String(), autoincrement=False, nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tp_of_pmt_id')
    )
    op.create_table('prepayment',
    sa.Column('prepayment_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.BigInteger(), nullable=False),
    sa.Column('tp_of_pmt_id', sa.BigInteger(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_number'], ['order.order_number'], ),
    sa.ForeignKeyConstraint(['tp_of_pmt_id'], ['type_of_payment.tp_of_pmt_id'], ),
    sa.PrimaryKeyConstraint('prepayment_id'),
    sa.UniqueConstraint('order_number'),
    sa.UniqueConstraint('tp_of_pmt_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prepayment')
    op.drop_table('type_of_payment')
    # ### end Alembic commands ###
