"""update agreement1

Revision ID: eff1347cfd29
Revises: 2d10f8529602
Create Date: 2024-03-20 22:54:20.281325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff1347cfd29'
down_revision = '2d10f8529602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreement', sa.Column('checked', sa.Boolean(), nullable=False))
    op.add_column('outlay_record', sa.Column('checked', sa.Boolean(), nullable=False))
    op.add_column('prepayment', sa.Column('checked', sa.Boolean(), nullable=False))
    op.add_column('report', sa.Column('checked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'checked')
    op.drop_column('prepayment', 'checked')
    op.drop_column('outlay_record', 'checked')
    op.drop_column('agreement', 'checked')
    # ### end Alembic commands ###
