"""role added

Revision ID: 93a496c50a97
Revises: ff982762d7a5
Create Date: 2024-03-07 18:44:56.272339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a496c50a97'
down_revision = 'ff982762d7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('role', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'role')
    # ### end Alembic commands ###
