"""create OutlayRecord4

Revision ID: e0996b5a43df
Revises: b92384419afb
Create Date: 2024-03-14 19:26:57.006291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0996b5a43df'
down_revision = 'b92384419afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('prepayment_tp_of_pmt_id_key', 'prepayment', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('prepayment_tp_of_pmt_id_key', 'prepayment', ['tp_of_pmt_id'])
    # ### end Alembic commands ###
