"""create OutlayRecord4

Revision ID: b92384419afb
Revises: 05f048351f1c
Create Date: 2024-03-14 19:11:53.007086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92384419afb'
down_revision = '05f048351f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('outlay_record_tp_of_pmt_id_key', 'outlay_record', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('outlay_record_tp_of_pmt_id_key', 'outlay_record', ['tp_of_pmt_id'])
    # ### end Alembic commands ###
