"""create Penalty3

Revision ID: 9b4d50bc4d70
Revises: e94946e2cbaf
Create Date: 2024-03-15 14:50:49.437116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4d50bc4d70'
down_revision = 'e94946e2cbaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'photo_of_agreement',
               existing_type=sa.VARCHAR(),
               nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'photo_of_agreement',
               existing_type=sa.VARCHAR(),
               nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###
