"""create_engineer_model2

Revision ID: 246a0ce69aa7
Revises: 7cce46aad603
Create Date: 2024-03-12 13:24:33.651149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246a0ce69aa7'
down_revision = '7cce46aad603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
