"""user_id_updated added

Revision ID: 9e1fd8b06583
Revises: ac2a0e213833
Create Date: 2024-03-07 20:14:35.178024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1fd8b06583'
down_revision = 'ac2a0e213833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
