"""create Penalty4

Revision ID: d2c196c2361c
Revises: 9b4d50bc4d70
Create Date: 2024-03-15 14:57:28.918806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c196c2361c'
down_revision = '9b4d50bc4d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
