"""update agreement

Revision ID: 2d10f8529602
Revises: 75378aace6bd
Create Date: 2024-03-20 21:23:18.475171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d10f8529602'
down_revision = '75378aace6bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreement', sa.Column('amount', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agreement', 'amount')
    # ### end Alembic commands ###
