"""upgrade Order1

Revision ID: 6cb9574b6abe
Revises: b30d1e168d95
Create Date: 2024-03-13 14:11:34.699686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb9574b6abe'
down_revision = 'b30d1e168d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'address')
    op.drop_column('order', 'model')
    op.drop_column('order', 'name_of_customer')
    op.drop_column('order', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('name_of_customer', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('address', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
