"""create OutlayRecord3

Revision ID: 05f048351f1c
Revises: 55e17930b564
Create Date: 2024-03-14 19:11:11.630024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f048351f1c'
down_revision = '55e17930b564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
