"""date to stationary

Revision ID: 0ac811af91a8
Revises: 5347f3a2bf55
Create Date: 2024-04-03 15:35:17.714162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac811af91a8'
down_revision = '5347f3a2bf55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stationary', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stationary', 'date')
    # ### end Alembic commands ###
