"""create OutlayRecord2

Revision ID: 55e17930b564
Revises: b4a10a290db2
Create Date: 2024-03-14 19:08:03.846879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e17930b564'
down_revision = 'b4a10a290db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outlay_record', sa.Column('order_number', sa.BigInteger(), nullable=False))
    op.add_column('outlay_record', sa.Column('tp_of_pmt_id', sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, 'outlay_record', ['tp_of_pmt_id'])
    op.drop_constraint('outlay_record_order_id_fkey', 'outlay_record', type_='foreignkey')
    op.create_foreign_key(None, 'outlay_record', 'type_of_payment', ['tp_of_pmt_id'], ['tp_of_pmt_id'])
    op.create_foreign_key(None, 'outlay_record', 'order', ['order_number'], ['order_number'])
    op.drop_column('outlay_record', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outlay_record', sa.Column('order_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'outlay_record', type_='foreignkey')
    op.drop_constraint(None, 'outlay_record', type_='foreignkey')
    op.create_foreign_key('outlay_record_order_id_fkey', 'outlay_record', 'order', ['order_id'], ['order_number'])
    op.drop_constraint(None, 'outlay_record', type_='unique')
    op.drop_column('outlay_record', 'tp_of_pmt_id')
    op.drop_column('outlay_record', 'order_number')
    # ### end Alembic commands ###
