"""create_tutor_model

Revision ID: ff982762d7a5
Revises: c79b0938ea4b
Create Date: 2024-03-06 19:11:56.673180

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ff982762d7a5"
down_revision = "c79b0938ea4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tutor",
        sa.Column(
            "tutors_number", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("link", sa.String(), autoincrement=False, nullable=True),
        sa.Column("name", sa.String(), autoincrement=False, nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_account.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("tutors_number"),
    )
    op.create_table(
        "order",
        sa.Column("order_number", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("tutors_number", sa.BigInteger(), nullable=True),
        sa.Column("stage_of_order", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("done", sa.Boolean(), nullable=True),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tutors_number"],
            ["tutor.tutors_number"],
        ),
        sa.PrimaryKeyConstraint("order_number"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order")
    op.drop_table("tutor")
    # ### end Alembic commands ###
