"""create Stationary

Revision ID: 66918c29ffe0
Revises: 19de3c5b99b1
Create Date: 2024-03-15 12:34:42.085260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66918c29ffe0'
down_revision = '19de3c5b99b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stationary',
    sa.Column('stationary_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.BigInteger(), nullable=False),
    sa.Column('state_engineers_number', sa.BigInteger(), nullable=False),
    sa.Column('priority', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('photo', sa.String(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(), autoincrement=False, nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_number'], ['order.order_number'], ),
    sa.ForeignKeyConstraint(['state_engineers_number'], ['state_engineer.state_engineers_number'], ),
    sa.PrimaryKeyConstraint('stationary_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stationary')
    # ### end Alembic commands ###
