"""create Penalty1

Revision ID: c152b1bf5ac4
Revises: f9a9a182c2da
Create Date: 2024-03-15 13:48:06.642266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c152b1bf5ac4'
down_revision = 'f9a9a182c2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_report_id_fkey', 'order', type_='foreignkey')
    op.drop_constraint('order_agreement_id_fkey', 'order', type_='foreignkey')
    op.drop_constraint('order_stationary_id_fkey', 'order', type_='foreignkey')
    op.drop_constraint('order_prepayment_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'report_id')
    op.drop_column('order', 'prepayment_id')
    op.drop_column('order', 'agreement_id')
    op.drop_column('order', 'stationary_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('stationary_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('agreement_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('prepayment_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('report_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_prepayment_id_fkey', 'order', 'prepayment', ['prepayment_id'], ['prepayment_id'])
    op.create_foreign_key('order_stationary_id_fkey', 'order', 'stationary', ['stationary_id'], ['stationary_id'])
    op.create_foreign_key('order_agreement_id_fkey', 'order', 'agreement', ['agreement_id'], ['agreement_id'])
    op.create_foreign_key('order_report_id_fkey', 'order', 'report', ['report_id'], ['report_id'])
    # ### end Alembic commands ###
