"""add agreement, fork, rejection 1

Revision ID: 8dc86fd09144
Revises: 4d91543d6c81
Create Date: 2024-03-13 16:33:10.648363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc86fd09144'
down_revision = '4d91543d6c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
