"""username added

Revision ID: bee2aed606bd
Revises: 93a496c50a97
Create Date: 2024-03-07 20:06:54.607115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee2aed606bd'
down_revision = '93a496c50a97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('user_name', sa.String(length=256), nullable=False))
    op.drop_index('ix_user_account_email', table_name='user_account')
    op.create_index(op.f('ix_user_account_user_name'), 'user_account', ['user_name'], unique=True)
    op.drop_column('user_account', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('email', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_account_user_name'), table_name='user_account')
    op.create_index('ix_user_account_email', 'user_account', ['email'], unique=True)
    op.drop_column('user_account', 'user_name')
    # ### end Alembic commands ###
