"""lol

Revision ID: 99565cef8f6c
Revises: eff1347cfd29
Create Date: 2024-03-20 23:04:36.362473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99565cef8f6c'
down_revision = 'eff1347cfd29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agreement', 'checked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agreement', 'checked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
