"""create Penalty5

Revision ID: 75378aace6bd
Revises: d2c196c2361c
Create Date: 2024-03-15 15:00:21.592251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75378aace6bd'
down_revision = 'd2c196c2361c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stationary', 'state_engineers_number',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stationary', 'state_engineers_number',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
